[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"

[[headers]]
  for = "/screeners/*"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
